export const CATEGORY_OPTIONS = {
  monster: {
    cr: [
      "1/8",
      "1/4",
      "1/2",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "15",
      "17",
      "20",
      "25",
      "30",
    ],
    size: ["Tiny", "Small", "Medium", "Large", "Huge", "Gargantuan"],
    type: [
      "Aberration",
      "Beast",
      "Celestial",
      "Construct",
      "Dragon",
      "Elemental",
      "Fey",
      "Fiend",
      "Giant",
      "Humanoid",
      "Monstrosity",
      "Ooze",
      "Plant",
      "Undead",
    ],
    alignment: [
      "Lawful Good",
      "Neutral Good",
      "Chaotic Good",
      "Lawful Neutral",
      "Neutral",
      "Chaotic Neutral",
      "Lawful Evil",
      "Neutral Evil",
      "Chaotic Evil",
    ],
    environment: [
      "Arctic",
      "Coast",
      "Desert",
      "Forest",
      "Grassland",
      "Mountain",
      "Swamp",
      "Underdark",
      "Underwater",
      "Urban",
    ],
  },
  item: {
    role: ["Combat", "Utility", "Roleplay"],
    type: [
      "Weapon",
      "Armor",
      "Potion",
      "Ring",
      "Rods",
      "Wands",
      "Wondrous Items",
      "Shield",
      "Scroll",
    ],
    rarity: [
      "common",
      "uncommon",
      "rare",
      "very rare",
      "legendary",
      "artifact",
    ],
    cursed: ["Yes", "No"],
    sentient: ["Yes", "No"],
  },
  character: {
    race: [
      "Human",
      "Elf",
      "Dwarf",
      "Halfling",
      "Dragonborn",
      "Gnome",
      "Half-Elf",
      "Half-Orc",
      "Tiefling",
      "Aasimar",
      "Tabaxi",
      "Triton",
      "Goliath",
      "Kenku",
    ],
    class: [
      "Barbarian",
      "Bard",
      "Cleric",
      "Druid",
      "Fighter",
      "Monk",
      "Paladin",
      "Ranger",
      "Rogue",
      "Sorcerer",
      "Warlock",
      "Wizard",
      "None",
    ],
    alignment: [
      "Lawful Good",
      "Neutral Good",
      "Chaotic Good",
      "Lawful Neutral",
      "Neutral",
      "Chaotic Neutral",
      "Lawful Evil",
      "Neutral Evil",
      "Chaotic Evil",
      "Unaligned",
    ],
    occupation: [
      "Merchant",
      "Noble",
      "Artisan",
      "Farmer",
      "Soldier",
      "Scholar",
      "Thief",
      "Adventurer",
      "Clergy",
      "Mage",
      "Bard",
      "Assassin",
    ],
    traits: [
      "Brave",
      "Cowardly",
      "Honest",
      "Deceitful",
      "Generous",
      "Greedy",
      "Wise",
      "Foolish",
      "Compassionate",
      "Ruthless",
    ],
  },
  location: {
    type: [
      "Dungeon",
      "Castle",
      "Town",
      "City",
      "Forest",
      "Mountain",
      "Cave",
      "Desert",
      "Swamp",
      "Underwater",
      "Ruins",
      "Temple",
    ],
    environment: [
      "Arctic",
      "Coastal",
      "Desert",
      "Forest",
      "Grassland",
      "Mountain",
      "Swamp",
      "Underdark",
      "Underwater",
      "Urban",
      "Astral Plane",
      "Ethereal Plane",
    ],
    features: [
      "Waterfall",
      "River",
      "Bridge",
      "Ancient Tree",
      "Statues",
      "Ruins",
      "Graveyard",
      "Mine",
      "Tower",
      "Portal",
    ],
    hazards: [
      "Traps",
      "Natural Hazards",
      "Infested",
      "Cursed",
      "Haunted",
      "Guarded",
      "Magical Anomalies",
      "Unstable Structures",
    ],
    secrets: [
      "Hidden Treasure",
      "Ancient Artifact",
      "Secret Room",
      "Hidden Passage",
      "Buried History",
      "Lost Magic",
      "Concealed Door",
      "Secret Society",
    ],
  },
};
